server:
  port: 8080
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  datasource:
    validation-query: SELECT 1
    test-on-borrow: true

logging:
  level:
    root: debug
    com.spring.mongodb: debug