server:
  port: 80

spring:
  application:
    name: spring-redis
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-idle: 10
      max-active: 50
      max-wait: 10000
      initial-size: 5
      # 默认的隔离级别为读写提交
      default-transaction-isolation: 2

  #redis配置
  redis:
    password:
    host: localhost
    database: 0
    port: 6379
    timeout: 1000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: 2000
        max-active: 10
    chanel: topic-test
#        time-between-eviction-runs: 5000
  #配置redis缓存管理器
  cache:
    type: redis
    cache-names: redisCache
    redis:
      cache-null-values: true #允许保存空值
      use-key-prefix: false #禁用前缀
      key-prefix:  #自定义前缀
      time-to-live: 600000



#Mybatis配置
mybatis:
  type-aliases-package: com.spring.redis.springredis.pojo
  mapper-locations: classpath*:mapper/**/*Mapper.xml

#日志配置
logging:
  level:
    root: debug
    org.springframework: info
    org.mybatis: debug
    com.spring.redis.springredis: debug

