
server:
  port: 8081
spring:
  datasource:
    name:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML
    suffix: .html
    encoding: utf-8
    prefix: classpath:/templates/



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myproject.springmybatis.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
    use-generated-keys: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
      mybatis: debug

