
server:
  port: 80
spring:
  datasource:
    name:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths: src/main/java


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myproject.springmybatis.model
logging:
  level:
    org:
      hibernate:
        SQL: debug

